// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgMXNYkcQirIasUkhCGavuEC6chdFG52I',
    appId: '1:658274940088:web:25262532899e36d17db04d',
    messagingSenderId: '658274940088',
    projectId: 'rentalcar02',
    authDomain: 'rentalcar02.firebaseapp.com',
    storageBucket: 'rentalcar02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABZNMlhv4XNmBC8T_sZwg8_UT3WPvQNGQ',
    appId: '1:658274940088:android:8482f9e1c72c0e587db04d',
    messagingSenderId: '658274940088',
    projectId: 'rentalcar02',
    storageBucket: 'rentalcar02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqA-4-I6w5uemWSrKGQiAIAHhkJXZdC04',
    appId: '1:658274940088:ios:47534391d5914fa57db04d',
    messagingSenderId: '658274940088',
    projectId: 'rentalcar02',
    storageBucket: 'rentalcar02.appspot.com',
    iosBundleId: 'com.example.rentalCarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqA-4-I6w5uemWSrKGQiAIAHhkJXZdC04',
    appId: '1:658274940088:ios:47534391d5914fa57db04d',
    messagingSenderId: '658274940088',
    projectId: 'rentalcar02',
    storageBucket: 'rentalcar02.appspot.com',
    iosBundleId: 'com.example.rentalCarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgMXNYkcQirIasUkhCGavuEC6chdFG52I',
    appId: '1:658274940088:web:b872dd1f8b9b70e47db04d',
    messagingSenderId: '658274940088',
    projectId: 'rentalcar02',
    authDomain: 'rentalcar02.firebaseapp.com',
    storageBucket: 'rentalcar02.appspot.com',
  );
}
